# Generated by Django 5.2.15 on 2026-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_propertyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="leased_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("available_at__isnull", False), ("status", "PENDING")),
                fields=["available_at"],
                name="job_retry_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyrecord",
            constraint=models.UniqueConstraint(
                fields=("job", "external_id"), name="uniq_property_per_job"
            ),
        ),
    ]
