# Generated by Django 5.2.15 on 2026-06-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_outboxevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("address_line1", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("postcode", models.CharField(max_length=16)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
