# Generated by Django 6.0.6 on 2026-07-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_reliability_fields_and_property_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
