# Generated by Django 6.0.7 on 2026-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_outbox_notify_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessHeartbeat",
            fields=[
                ("name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("beat_at", models.DateTimeField()),
            ],
        ),
    ]
